# Configuração para Banco de Dados Permanente (Arquivo físico)
spring.datasource.url=jdbc:h2:file:./data/salaodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mantém o console do H2 ativo para consultas
spring.h2.console.enabled=true

# Hibernate: 'update' apenas atualiza a estrutura sem apagar os dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- DIRETORIO ---
upload.dir=C:/salao_Loana/fotos_clientes